#!/bin/bash

if [ $# -ne 1 ]
then
        echo "Niepoprawna liczba argumentów."
        exit 1
fi

if [ ! -d $1 ]
then
        echo "$1 nie jest katalogiem!"
        exit 1
fi

find $1 -type f -print | awk -F ' /*\.exe*/ {split($0,"."," "); print $1}'
